### ISSUE TITLE
Mention parent selector will not be changed by `@at-root {}` in the docs.

### ISSUE THREAD

**Issue by miguel-leon** [sass/sass-site#1370]
Hi again, sorry to bother.

The [parent selector documentation](https://sass-lang.com/documentation/style-rules/parent-selector/#in-sass-script) mentions:

> If the `&` expression is used outside any style rules, it returns `null`. Since `null` is [falsey](https://sass-lang.com/documentation/at-rules/control/if#truthiness-and-falsiness), this means you can easily use it to determine whether a mixin is being called in a style rule or not.

So I was using a mixin in a manner similar to the example that follows that paragraph.

Then I included that mixin inside an `@at-root { ... }` assuming the check in the mixin would still stand. i.e. `&` would be falsey. Like this:
```scss
.some-selector {
  $_: &; // save for later use.
  @at-root {
    @include checking-mixin { /* use $_ here */ }
  }
}
```

But after debugging I realized `@at-root` doesn't change `&` if used by itself without a selector. I assume this is intended.

Could we add this little bit of information to highlight that mixin checks to `&` won't work the same way as if performed at the actual root, outside any rules?

Also, bonus question, there's no way to achieve something like this right? `checking-mixin` has to be called in the actual root and `.some-selector` has to be duplicated inside the content, right? Like so:

```scss
.some-selector { ... }

@include checking-mixin {
  .some-selector { ... }
}
```

**Comment by nex3** [comment]
https://github.com/sass/sass-site/pull/1371 is a little more explicit about how the `&` expression works with `@at-root`.

> Also, bonus question, there's no way to achieve something like this right? `checking-mixin` has to be called in the actual root and `.some-selector` has to be duplicated inside the content, right? Like so:
> 
> .some-selector { ... }
> 
> @include checking-mixin {
>   .some-selector { ... }
> }

I'm not sure what you're trying to achieve here. Can you provide more context?

**Comment by miguel-leon** [comment]
Hi, thanks. I appreciate the update in the documentation.

As for the question, I'll give a more practical example of what I'm doing, maybe I'm approaching this all wrong.

I have these utility selector mixins for surrogate buttons only and for all buttons which also includes the `button` tag as a selector.
```scss
@mixin surrogate-buttons {
  [role="button"], .btn {
    @content;
  }
}

@mixin all-buttons {
  $_: &;
  @at-root {
    @include surrogate-buttons {
      #{$_} :where(button, &) {
        @content;
      }
    }
  }
}
```
I can include styles for all buttons like so:
```scss
@include all-buttons {
  font: inherit;
}
```
and get:
```css
:where(button, [role=button], .btn) {
  font: inherit;
}
```
Then let's say I have a `span.special` with styles, which I'd like to also take particular styles when inside a button. But doing the following:
```scss
span.special {
  // other styles.
  
  $_: &;
  @at-root {
    @include all-buttons {
      @at-root & #{$_} {
        color: red;
      }
    }
  }
}
```
incorrectly gets me:
```css
span.special :where(button, [role=button], .btn) span.special {
  color: red;
}
```

The only way I've found is to duplicate `span.special` inside an `all-buttons` at the actual root:
```scss
@include all-buttons {
  span.special {
    // styles for span.special's inside buttons.
    color: blue;
  }
}
```

I just don't like to repeat selectors because I might change them after, or they can be more complex.
[Playground](https://sass-lang.com/playground/#eJydUslqwzAQvesrhjS4DcQOvroU/B8hBNmZxgPqKEgyTQn+944XZSuBtjoIpLeOUJ6XH3QkBt86Z/c6YFq1IVj2cFIAa2cNvs3Gq9lmCVkVeEAAytpyQA6vcupUp9TkpI258ZhvC0h6UqlD6qwNUU9cm3aHD6L79XSabzsoPht0+DKCS0gWZ/y2RL86FfexUsy4L/UusgKIxZlELFR/0Jz5A9akzUAxxJg2SPtGmHkfsFqBD18GvcgdXAsE/M2k9y0GMHKTadzLcI/znr109ySWk112FtXWWFeAw91f3+THC/yjwZRemRbjv/gGCSC4Fg==)
