### ISSUE TITLE
Mistake in Maps Immutability example

### ISSUE THREAD

**Issue by evilhomby** [sass/sass-site#351]
The output in console is  `("firefox": moz, "safari": webkit, "ie": ms)`

```scss
$prefixes-by-browser: ("firefox": moz, "safari": webkit, "ie": ms);

@mixin add-browser-prefix($browser, $prefix) {
  $prefixes: map-merge($prefixes-by-browser, ($browser: $prefix));
}

@include add-browser-prefix("opera", o);
@debug $prefixes-by-browser;
// ("firefox": moz, "safari": webkit, "ie": ms, "opera": o)
```

Is it correct to change like this? :)

```scss
$prefixes-by-browser: ("firefox": moz, "safari": webkit, "ie": ms);

@function add-browser-prefix($browser, $prefix) {
  @return map-merge($prefixes-by-browser, ($browser: $prefix));
}

$prefixes-by-browser: add-browser-prefix("opera", o);
@debug $prefixes-by-browser;
// ("firefox": moz, "safari": webkit, "ie": ms, "opera": o)
```
