### ISSUE TITLE
Flow Control rules scope difference for parameters and content

### ISSUE THREAD

**Issue by MartijnCuppens** [sass/sass-site#509]
There is a different scope for content variables (like `$background`) or parameters (like `$value`) in the following example:

```scss
@each $value in $map {
  $background: $value;
}
```

The following demo should make things a little clearer: https://www.sassmeister.com/gist/c329d24d5a030f869a90c019075aa4f6?token=203daf3221af119f9e7a6898b97e14608c077727&scope=gist,read:user

This isn't really documented in [the docs](https://sass-lang.com/documentation/variables#scope).

Also see https://github.com/twbs/bootstrap/pull/32492

**Comment by Awjin** [comment]
I'm not able to see the example Sass code in Sassmeister, only the outputted CSS. Could post the Sass here?

**Comment by MartijnCuppens** [comment]
```scss
$background: blue;
$value: purple;

$theme-colors: (
  "primary":    yellow,
  "secondary":  red,
);

@each $state, $value in $theme-colors {
  $background: $value;
  .alert-#{$state} {
      background: $value;
  }
}

.bg {
    background: $background; // Overridden
    value: $value; // Not overridden
}
```
becomes
```css
.alert-primary {
  background: yellow;
}

.alert-secondary {
  background: red;
}

.bg {
  background: red;
  value: purple;
}
```

**Comment by Awjin** [comment]
Thanks for clarifying. This is [working as intended](https://sass-lang.com/documentation/variables#flow-control-scope). In this case, each `$background: $value` assignment in the `each` statement updates the global `$background` value. 

As for `value` in—

```scss
.bg {
    background: $background; // Overridden
    value: $value; // Not overridden
}
```

—we'd expect`$value` to not be overridden, since it doesn't get reassigned  in the `each` statement.
